### PR TITLE
Update to metaschema-java 0.11.0

### PR DESCRIPTION
**Pull request by david-waltermire-nist**
# Committer Notes

Adjustments to ensure working order with metaschema-java 0.11.0.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/usnistgov/oscal-cli/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you set "[Allow edits and access to secrets by maintainers
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/oscal-cli/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- ~Have you included examples of how to use your new feature(s)?~
- ~Have you updated all website and readme documentation affected by the changes you made?~

### CODE REVIEW

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist This fixes usnistgov/liboscal-java#119, which was reported against the wrong repo. Can you add this issue to the fixed lists here?

**Comment by david-waltermire-nist** [comment]
The PR usnistgov/metaschema-java#184 resolved #109.

@aj-stein-nist Would you please add #109 as fixed by this PR?

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist Would you please add #128 as fixed by this PR?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist Would you please add #128 as fixed by this PR?

Done.

**Review by aj-stein-nist — COMMENTED** [review]
I had some weirdness with the UI, but this looks good to me, thanks @david-waltermire-nist.

**Pull request merged**
